package com.kisakcod.android.app

import android.app.ActivityManager
import android.content.Context
import android.os.Build
import kotlin.math.min

/**
 * Detects the phone's class (low / mid / high / flagship) and generates an
 * engine configuration ("android_launcher.cfg") with safe dvar settings, so the
 * game is playable on weak devices and looks great on strong ones.
 *
 * All dvar names below are real KisakCOD dvars (see src/gfx_d3d/r_dvars.cpp).
 */
object PerfProfile {

    enum class Tier { LOW, MID, HIGH, FLAGSHIP }

    data class DeviceInfo(
        val tier: Tier,
        val socLabel: String,
        val ramMb: Long,
        val cores: Int
    )

    fun detect(context: Context): DeviceInfo {
        val am = context.getSystemService(Context.ACTIVITY_SERVICE) as ActivityManager
        val mi = ActivityManager.MemoryInfo()
        am.getMemoryInfo(mi)
        val ramMb = mi.totalMem / (1024 * 1024)
        val cores = Runtime.getRuntime().availableProcessors()
        val soc = socLabel()

        val tier = when {
            isFlagship(soc, ramMb, cores) -> Tier.FLAGSHIP
            isHigh(soc, ramMb, cores) -> Tier.HIGH
            ramMb >= 3000 && cores >= 6 -> Tier.MID
            else -> Tier.LOW
        }
        return DeviceInfo(tier, soc, ramMb, cores)
    }

    private fun socLabel(): String {
        val parts = mutableListOf<String>()
        if (Build.VERSION.SDK_INT >= 31 && !Build.SOC_MODEL.isNullOrBlank()) parts.add(Build.SOC_MODEL)
        if (Build.VERSION.SDK_INT >= 31 && !Build.SOC_MANUFACTURER.isNullOrBlank()) parts.add(Build.SOC_MANUFACTURER)
        if (parts.isEmpty()) parts.add(Build.HARDWARE)
        if (parts.isEmpty()) parts.add(Build.MODEL)
        return parts.joinToString(" ")
    }

    private fun knownSoC(soc: String, tokens: List<String>) =
        tokens.any { soc.lowercase().contains(it.lowercase()) }

    private fun isFlagship(soc: String, ramMb: Long, cores: Int): Boolean {
        val hot = listOf(
            "snapdragon 8", "dimensity 9", "tensor g", "exynos 2", "exynos 5", "apple",
            "kirin 9", "mali-g9", "adreno 7", "adreno 8", "xgbe", "mt9"
        )
        return ramMb >= 7000 && (knownSoC(soc, hot) || cores >= 8)
    }

    private fun isHigh(soc: String, ramMb: Long, cores: Int): Boolean {
        val mid = listOf(
            "snapdragon 7", "dimensity 8", "exynos 1", "mtk6983", "mt6", "kirin 8", "adreno 6"
        )
        return ramMb >= 5000 && (knownSoC(soc, mid) || cores >= 8)
    }

    /** Generates the engine cfg text for the selected tier. */
    fun engineCfg(tier: Tier): String {
        val sb = StringBuilder()
        sb.append("// android_launcher.cfg — generated by KisakCOD launcher (perf profile: ")
        sb.append(tier.name.lowercase()).append(")\n")
        when (tier) {
            Tier.LOW -> {
                sb.append("seta r_picmip_manual 1\n")
                sb.append("seta r_picmip 2\n")
                sb.append("seta r_drawSun 0\n")
                sb.append("seta r_drawWater 0\n")
                sb.append("seta r_drawDecals 0\n")
                sb.append("seta r_spotLightShadows 0\n")
                sb.append("seta r_envMapSpecular 0\n")
                sb.append("seta r_fastSkin 1\n")
                sb.append("seta r_vsync 0\n")
                sb.append("seta com_maxfps 30\n")
            }
            Tier.MID -> {
                sb.append("seta r_picmip_manual 1\n")
                sb.append("seta r_picmip 1\n")
                sb.append("seta r_drawSun 0\n")
                sb.append("seta r_drawWater 1\n")
                sb.append("seta r_drawDecals 1\n")
                sb.append("seta r_spotLightShadows 0\n")
                sb.append("seta r_envMapSpecular 0\n")
                sb.append("seta r_fastSkin 1\n")
                sb.append("seta r_vsync 0\n")
                sb.append("seta com_maxfps 60\n")
            }
            Tier.HIGH -> {
                sb.append("seta r_picmip_manual 1\n")
                sb.append("seta r_picmip 0\n")
                sb.append("seta r_drawSun 1\n")
                sb.append("seta r_drawWater 1\n")
                sb.append("seta r_drawDecals 1\n")
                sb.append("seta r_spotLightShadows 1\n")
                sb.append("seta r_envMapSpecular 0\n")
                sb.append("seta r_vsync 1\n")
                sb.append("seta com_maxfps 0\n")
            }
            Tier.FLAGSHIP -> {
                sb.append("seta r_picmip_manual 1\n")
                sb.append("seta r_picmip 0\n")
                sb.append("seta r_drawSun 1\n")
                sb.append("seta r_drawWater 1\n")
                sb.append("seta r_drawDecals 1\n")
                sb.append("seta r_spotLightShadows 1\n")
                sb.append("seta r_envMapSpecular 1\n")
                sb.append("seta r_vsync 1\n")
                sb.append("seta com_maxfps 0\n")
            }
        }
        return sb.toString()
    }

    /** Writes android_launcher.cfg next to the game data (engine exec's it on start). */
    fun writeEngineCfg(context: Context, tier: Tier) {
        try {
            val cfg = GamePaths.gameRoot(context)
            val f = java.io.File(cfg, "android_launcher.cfg")
            f.writeText(engineCfg(tier))
            // also append exec line to config_mp.cfg if present so it applies automatically
            val mpCfg = java.io.File(cfg, "config_mp.cfg")
            if (mpCfg.exists() && !mpCfg.readText().contains("android_launcher.cfg")) {
                mpCfg.appendText("\nexec android_launcher.cfg\n")
            }
        } catch (e: Exception) {
            // non-fatal: engine still boots with defaults
        }
    }

    fun describe(info: DeviceInfo): String {
        val t = when (info.tier) {
            Tier.LOW -> "Слабый"
            Tier.MID -> "Средний"
            Tier.HIGH -> "Мощный"
            Tier.FLAGSHIP -> "Флагман"
        }
        return "Профиль: $t · SoC: ${info.socLabel} · RAM: ${min(info.ramMb, 99999)} МБ · Ядра: ${info.cores}"
    }
}